"use client";
import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";

type Repository={id:number;name:string;owner:string;fullName:string;defaultBranch:string;private:boolean};
type Target="github"|"wordpress";

export function OnboardingForm({initialInstallationId=""}:{initialInstallationId?:string}){
  const router=useRouter();
  const[target,setTarget]=useState<Target>("github"),[step,setStep]=useState(initialInstallationId?2:1);
  const[installation,setInstallation]=useState(initialInstallationId),[repos,setRepos]=useState<Repository[]>([]),[selected,setSelected]=useState("");
  const[busy,setBusy]=useState(false),[message,setMessage]=useState("");
  const[details,setDetails]=useState({name:"",url:"",siteType:"publisher",wordpressApiUrl:"",wordpressUsername:"",wordpressApplicationPassword:"",keywords:"",competitors:""});
  const repo=useMemo(()=>repos.find(item=>item.fullName===selected),[repos,selected]);
  const update=(key:keyof typeof details,value:string)=>setDetails(current=>({...current,[key]:value}));

  useEffect(()=>{if(target!=="github"||!installation)return;setBusy(true);fetch(`/api/v1/github/repositories?installationId=${installation}`).then(r=>r.json()).then(body=>{setRepos(body.data||[]);if(body.data?.length)setSelected(body.data[0].fullName);setMessage(body.error?.message||"")}).finally(()=>setBusy(false))},[installation,target]);
  async function install(){const response=await fetch("/api/v1/github/install"),body=await response.json();if(body.data?.url)location.href=body.data.url;else setMessage(body.error?.message||"GitHub App is not configured")}
  async function submit(){
    if(target==="github"&&!repo)return setMessage("Select an authorized repository");
    setBusy(true);setMessage("");
    const publishingTarget=target==="github"?{type:"github",repositoryOwner:repo!.owner,repositoryName:repo!.name,defaultBranch:repo!.defaultBranch,githubInstallationId:Number(installation)}:{type:"wordpress",apiUrl:details.wordpressApiUrl,username:details.wordpressUsername,applicationPassword:details.wordpressApplicationPassword};
    const response=await fetch("/api/v1/sites",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:details.name,url:details.url,publishingTarget,siteType:details.siteType,initialKeywords:details.keywords.split("\n").map(x=>x.trim()).filter(Boolean),competitors:details.competitors.split("\n").map(x=>x.trim()).filter(Boolean)})});
    const body=await response.json();setBusy(false);if(!response.ok)return setMessage(body.error?.message||"Could not connect site");router.push(`/dashboard/sites/${body.data.id}`);router.refresh();
  }
  const steps=["Publishing source","Connection","Website","Data sources","Market","Readiness"];
  return <><div className="wizard-steps">{steps.map((label,index)=><button type="button" className={step===index+1?"active":step>index+1?"done":""} key={label} onClick={()=>step>index+1&&setStep(index+1)}><span>{step>index+1?"✓":index+1}</span>{label}</button>)}</div><div className="split"><div className="card form"><span className="eyebrow">Step {step} of {steps.length}</span>
    {step===1&&<><h2>How should SEOForge manage content?</h2><p>Choose one publishing source. You can connect another site separately later.</p><div className="target-choice"><button type="button" className={`card ${target==="github"?"selected":""}`} onClick={()=>setTarget("github")}><strong>GitHub repository</strong><span>Branches, protected PRs and automatic hosting deployments.</span></button><button type="button" className={`card ${target==="wordpress"?"selected":""}`} onClick={()=>setTarget("wordpress")}><strong>WordPress blog</strong><span>Posts, pages and media through the WordPress REST API.</span></button></div><button type="button" className="button primary" onClick={()=>setStep(2)}>Continue with {target==="github"?"GitHub":"WordPress"}</button></>}
    {step===2&&target==="github"&&<><h2>Authorize a repository</h2><p>Install the least-privilege GitHub App, then select an authorized repository.</p><button type="button" className="button secondary" onClick={install}>Install or manage GitHub App</button><div className="field"><label>GitHub installation ID</label><input value={installation} onChange={e=>setInstallation(e.target.value)} inputMode="numeric"/></div><div className="field"><label>Repository</label><select value={selected} onChange={e=>setSelected(e.target.value)} disabled={busy}>{repos.map(item=><option key={item.id} value={item.fullName}>{item.fullName}{item.private?" · private":""}</option>)}</select></div><div className="notice">{repo?`Permission verified: ${repo.fullName}, branch ${repo.defaultBranch}.`:"Install the app to retrieve repositories."}</div><button type="button" className="button primary" disabled={!repo} onClick={()=>setStep(3)}>Validate & continue</button></>}
    {step===2&&target==="wordpress"&&<><h2>Connect WordPress securely</h2><p>Create a dedicated WordPress user and Application Password. Never enter the user’s normal login password.</p><div className="field"><label>WordPress site or API URL</label><input type="url" value={details.wordpressApiUrl} onChange={e=>update("wordpressApiUrl",e.target.value)} placeholder="https://blog.example.com"/></div><div className="field"><label>WordPress username</label><input value={details.wordpressUsername} onChange={e=>update("wordpressUsername",e.target.value)} autoComplete="username"/></div><div className="field"><label>Application Password</label><input type="password" value={details.wordpressApplicationPassword} onChange={e=>update("wordpressApplicationPassword",e.target.value)} autoComplete="new-password"/></div><div className="notice">SEOForge verifies `/wp-json/wp/v2/users/me`, encrypts the credential, and keeps it away from models.</div><button type="button" className="button primary" disabled={!details.wordpressApiUrl||!details.wordpressUsername||details.wordpressApplicationPassword.length<8} onClick={()=>setStep(3)}>Verify during setup</button></>}
    {step===3&&<><h2>Identify the live website</h2><div className="field"><label>Site name</label><input value={details.name} onChange={e=>update("name",e.target.value)} required placeholder="Acme Blog"/></div><div className="field"><label>Live website URL</label><input value={details.url} onChange={e=>update("url",e.target.value)} type="url" required placeholder="https://www.example.com"/></div><div className="field"><label>Site mode</label><select value={details.siteType} onChange={e=>update("siteType",e.target.value)}><option value="saas">SaaS</option><option value="publisher">Publisher</option><option value="ecommerce">Ecommerce</option><option value="local">Local business</option><option value="agency">Agency</option><option value="other">Other</option></select></div><button type="button" className="button primary" disabled={!details.name||!details.url} onClick={()=>setStep(4)}>Continue</button></>}
    {step===4&&<><h2>Connect measurement providers</h2><div className="readiness-list"><span>Google Search Console + GA4</span><a href="/api/oauth/google/start">Connect Google →</a><span>DataForSEO rankings and SERPs</span><a href="/dashboard/providers">Add credentials →</a><span>Bing / IndexNow</span><a href="/dashboard/providers">Configure →</a></div><button type="button" className="button primary" onClick={()=>setStep(5)}>Continue</button></>}
    {step===5&&<><h2>Define the first market baseline</h2><div className="field"><label>Priority keywords (one per line)</label><textarea value={details.keywords} onChange={e=>update("keywords",e.target.value)} rows={7}/></div><div className="field"><label>Competitor domains (one per line)</label><textarea value={details.competitors} onChange={e=>update("competitors",e.target.value)} rows={5}/></div><button type="button" className="button primary" onClick={()=>setStep(6)}>Review readiness</button></>}
    {step===6&&<><h2>Run readiness and create the baseline</h2><div className="readiness-list"><span>Publishing source</span><b>{target==="github"?(repo?"GitHub ready":"Blocked"):"WordPress will verify"}</b><span>Production changes</span><b>Human approval required</b><span>Analytics and rank providers</span><b>Checked before autonomy</b></div><div className="notice">WordPress changes are prepared as drafts. GitHub changes use protected pull requests. Neither path publishes without explicit approval.</div><button type="button" className="button primary" disabled={busy||(target==="github"&&!repo)} onClick={submit}>{busy?"Verifying and creating…":"Create site & baseline"}</button></>}
    {message&&<div className="notice">{message}</div>}</div><div className="card"><span className="eyebrow">Publishing target</span><h2>{target==="github"?"Protected repository workflow":"WordPress REST workflow"}</h2><p>{target==="github"?"SEOForge proposes branches and pull requests. Your connected host can deploy automatically after an approved merge.":"SEOForge reads the existing editorial style and prepares posts, pages and media as reviewable drafts."}</p><div className="evidence-list"><div><strong>Target</strong><span>{target}</span></div><div><strong>Connection</strong><span>{target==="github"?(repo?.fullName||"Not selected"):(details.wordpressApiUrl||"Not entered")}</span></div><div><strong>Authority</strong><span>Human approval before publishing</span></div></div></div></div></>;
}
