"use client";
import { useRef, useState } from "react";
import { GoogleGenAI } from "@google/genai";

function toBase64(bytes:Uint8Array){let binary="";for(let i=0;i<bytes.length;i++)binary+=String.fromCharCode(bytes[i]!);return btoa(binary);}
function fromBase64(value:string){const binary=atob(value);const bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);return bytes;}
function pcm16(input:Float32Array,inputRate:number){const ratio=inputRate/16000;const length=Math.floor(input.length/ratio);const out=new Int16Array(length);for(let i=0;i<length;i++){const sample=input[Math.floor(i*ratio)]||0;out[i]=Math.max(-32768,Math.min(32767,Math.round(sample*32767)));}return new Uint8Array(out.buffer);}

export function VoiceReview(){const[status,setStatus]=useState("Ready");const[transcript,setTranscript]=useState<string[]>([]);const session=useRef<any>(null);const audio=useRef<AudioContext|null>(null);const stream=useRef<MediaStream|null>(null);const processor=useRef<ScriptProcessorNode|null>(null);
  async function play(base64:string){const context=audio.current||(audio.current=new AudioContext({sampleRate:24000}));const bytes=fromBase64(base64);const samples=new Int16Array(bytes.buffer);const buffer=context.createBuffer(1,samples.length,24000);const channel=buffer.getChannelData(0);for(let i=0;i<samples.length;i++)channel[i]=(samples[i]||0)/32768;const source=context.createBufferSource();source.buffer=buffer;source.connect(context.destination);source.start();}
  async function start(){setStatus("Authorizing…");const tokenResponse=await fetch("/api/v1/live/token",{method:"POST"});const payload=await tokenResponse.json();if(!tokenResponse.ok){setStatus(payload.error?.message||"Unavailable");return;}const ai=new GoogleGenAI({apiKey:payload.data.token});session.current=await ai.live.connect({model:payload.data.model,config:{responseModalities:["AUDIO"],inputAudioTranscription:{},outputAudioTranscription:{},sessionResumption:{},contextWindowCompression:{slidingWindow:{}}},callbacks:{onopen:()=>setStatus("Listening"),onmessage:(message:any)=>{const content=message.serverContent;if(content?.interrupted&&audio.current){audio.current.close();audio.current=null;}for(const part of content?.modelTurn?.parts||[])if(part.inlineData?.data)void play(part.inlineData.data);if(content?.inputTranscription?.text)setTranscript(items=>[...items,`You: ${content.inputTranscription.text}`]);if(content?.outputTranscription?.text)setTranscript(items=>[...items,`SEOForge: ${content.outputTranscription.text}`]);},onerror:(error:any)=>setStatus(`Error: ${error.message}`),onclose:()=>setStatus("Closed")}} as any);
    stream.current=await navigator.mediaDevices.getUserMedia({audio:{channelCount:1,echoCancellation:true,noiseSuppression:true}});const context=audio.current||(audio.current=new AudioContext());const source=context.createMediaStreamSource(stream.current);const node=context.createScriptProcessor(4096,1,1);node.onaudioprocess=(event)=>{if(!session.current)return;const bytes=pcm16(event.inputBuffer.getChannelData(0),context.sampleRate);session.current.sendRealtimeInput({audio:{data:toBase64(bytes),mimeType:"audio/pcm;rate=16000"}});};source.connect(node);node.connect(context.destination);processor.current=node;
  }
  function stop(){processor.current?.disconnect();processor.current=null;stream.current?.getTracks().forEach(track=>track.stop());stream.current=null;session.current?.sendRealtimeInput({audioStreamEnd:true});session.current?.close();session.current=null;setStatus("Ready");}
  return <div className="card"><span className="eyebrow">Live review</span><h2 style={{marginBottom:8}}>Talk through the evidence.</h2><p>Voice can explain and stage a decision. It cannot approve, merge, deploy, or roll back.</p><div style={{display:"flex",gap:8,marginTop:16}}><button className="button primary" onClick={start} disabled={status==="Listening"}>Start voice</button><button className="button secondary" onClick={stop}>Stop</button></div><small style={{display:"block",marginTop:8}}>Status: {status}</small>{transcript.length>0&&<div style={{marginTop:12,maxHeight:140,overflow:"auto",fontSize:12}}>{transcript.slice(-8).map((line,i)=><p key={i}>{line}</p>)}</div>}</div>;
}
