create type public.integration_environment as enum ('test','live');

alter table public.workspaces add column if not exists environment public.integration_environment not null default 'live';
alter table public.sites add column if not exists site_type text not null default 'other' check(site_type in ('saas','local','ecommerce','publisher','agency','other'));
alter table public.sites add column if not exists readiness jsonb not null default '{"ready":false,"checks":{}}';

create table public.keyword_clusters(id uuid primary key default gen_random_uuid(),site_id uuid not null references public.sites(id) on delete cascade,name text not null,intent text,centroid text,created_at timestamptz not null default now(),unique(site_id,name));
alter table public.tracked_queries add column if not exists cluster_id uuid references public.keyword_clusters(id) on delete set null;
alter table public.tracked_queries add column if not exists device text not null default 'desktop' check(device in ('desktop','mobile'));
alter table public.tracked_queries add column if not exists search_engine text not null default 'google';
alter table public.tracked_queries add column if not exists tags text[] not null default '{}';

create table public.site_health_scores(id uuid primary key default gen_random_uuid(),site_id uuid not null references public.sites(id) on delete cascade,captured_at timestamptz not null default now(),score numeric(5,2) not null check(score between 0 and 100),categories jsonb not null,evidence_ids uuid[] not null default '{}',unique(site_id,captured_at));
create table public.daily_site_metrics(id uuid primary key default gen_random_uuid(),site_id uuid not null references public.sites(id) on delete cascade,metric_date date not null,source text not null,clicks bigint not null default 0,impressions bigint not null default 0,sessions bigint not null default 0,conversions numeric not null default 0,revenue numeric not null default 0,ctr numeric not null default 0,average_position numeric,indexed_pages integer,payload_hash text not null,unique(site_id,metric_date,source));
create table public.page_metrics(id uuid primary key default gen_random_uuid(),site_id uuid not null references public.sites(id) on delete cascade,url text not null,metric_date date not null,source text not null,clicks bigint not null default 0,impressions bigint not null default 0,sessions bigint not null default 0,conversions numeric not null default 0,lcp numeric,inp numeric,cls numeric,index_state text,unique(site_id,url,metric_date,source));
create table public.competitors(id uuid primary key default gen_random_uuid(),site_id uuid not null references public.sites(id) on delete cascade,domain text not null,label text,visibility numeric,last_observed_at timestamptz,unique(site_id,domain));
create table public.backlink_observations(id uuid primary key default gen_random_uuid(),site_id uuid not null references public.sites(id) on delete cascade,source_url text not null,target_url text not null,anchor text,domain_rank numeric,first_seen timestamptz,last_seen timestamptz,status text not null default 'active',toxicity_score numeric,toxicity_evidence jsonb not null default '[]',unique(site_id,source_url,target_url));
create table public.ai_citation_probes(id uuid primary key default gen_random_uuid(),site_id uuid not null references public.sites(id) on delete cascade,provider text not null,query text not null,captured_at timestamptz not null,response_hash text not null,cited boolean not null,citation_urls text[] not null default '{}',visibility_score numeric,synthetic boolean not null default true,unique(site_id,provider,query,captured_at));
create table public.internal_link_edges(id uuid primary key default gen_random_uuid(),site_id uuid not null references public.sites(id) on delete cascade,source_url text not null,target_url text not null,anchor text,followed boolean not null default true,captured_at timestamptz not null,unique(site_id,source_url,target_url,anchor));

create table public.agent_events(id uuid primary key default gen_random_uuid(),run_id uuid not null references public.agent_runs(id) on delete cascade,site_id uuid not null references public.sites(id) on delete cascade,role text not null,event_type text not null,status text,tool_name text,current_target text,decision_summary text,evidence_count integer not null default 0,input_tokens bigint not null default 0,output_tokens bigint not null default 0,estimated_cost numeric not null default 0,retry_number integer not null default 0,error_code text,error_message text,created_at timestamptz not null default now());
alter table public.findings add column if not exists impact_score numeric not null default 0;
alter table public.findings add column if not exists assigned_to uuid references auth.users(id) on delete set null;
alter table public.findings add column if not exists deferred_until timestamptz;
alter table public.findings add column if not exists duplicate_group_id uuid;
create table public.finding_events(id uuid primary key default gen_random_uuid(),finding_id uuid not null references public.findings(id) on delete cascade,actor_user_id uuid references auth.users(id),action text not null,from_status text,to_status text,note text,created_at timestamptz not null default now());

create table public.content_items(id uuid primary key default gen_random_uuid(),site_id uuid not null references public.sites(id) on delete cascade,title text not null,item_type text not null,status text not null default 'idea',target_query text,brief jsonb not null default '{}',scheduled_for date,approved_by uuid references auth.users(id),approved_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.experiment_observations(id uuid primary key default gen_random_uuid(),experiment_id uuid not null references public.experiments(id) on delete cascade,observed_at timestamptz not null,metric_value numeric not null,cohort text not null default 'all',source text not null,metadata jsonb not null default '{}');
create table public.proposal_file_reviews(proposal_id uuid not null references public.proposals(id) on delete cascade,path text not null,approved boolean not null default false,reviewed_by uuid references auth.users(id),reviewed_at timestamptz,primary key(proposal_id,path));
create table public.brand_profile_versions(id uuid primary key default gen_random_uuid(),site_id uuid not null references public.sites(id) on delete cascade,version integer not null,profile jsonb not null,source_hashes text[] not null default '{}',status text not null default 'draft',approved_by uuid references auth.users(id),approved_at timestamptz,created_at timestamptz not null default now(),unique(site_id,version));
create table public.knowledge_documents(id uuid primary key default gen_random_uuid(),site_id uuid not null references public.sites(id) on delete cascade,kind text not null,source_url text,source_path text,content_hash text not null,summary text not null,object_key text,expires_at timestamptz,replaced_by uuid references public.knowledge_documents(id),created_at timestamptz not null default now());

create table public.notification_destinations(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces(id) on delete cascade,channel text not null check(channel in ('email','slack','webhook')),label text not null,encrypted_config jsonb not null,events text[] not null default '{}',active boolean not null default true,created_at timestamptz not null default now());
create table public.notification_deliveries(id uuid primary key default gen_random_uuid(),destination_id uuid not null references public.notification_destinations(id) on delete cascade,event_type text not null,payload_hash text not null,status text not null,attempts integer not null default 0,last_error text,created_at timestamptz not null default now(),delivered_at timestamptz);
create table public.automation_schedules(id uuid primary key default gen_random_uuid(),site_id uuid not null references public.sites(id) on delete cascade,kind text not null,cron text not null,timezone text not null default 'UTC',enabled boolean not null default true,budget_limit numeric,settings jsonb not null default '{}',created_at timestamptz not null default now(),unique(site_id,kind));
create table public.workspace_budgets(workspace_id uuid primary key references public.workspaces(id) on delete cascade,monthly_spend_limit numeric,alert_percent integer not null default 80,hard_stop boolean not null default true,updated_at timestamptz not null default now());

create table public.developer_applications(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces(id) on delete cascade,name text not null,environment public.integration_environment not null,redirect_uris text[] not null default '{}',scopes text[] not null,client_id text not null unique,client_secret_hash text,status text not null default 'active',created_at timestamptz not null default now());
create table public.api_tokens(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces(id) on delete cascade,application_id uuid references public.developer_applications(id) on delete cascade,environment public.integration_environment not null,label text not null,token_prefix text not null,last_four text not null,token_hash text not null unique,scopes text[] not null,site_ids uuid[] not null default '{}',ip_allowlist cidr[] not null default '{}',expires_at timestamptz not null,revoked_at timestamptz,last_used_at timestamptz,created_by uuid references auth.users(id),created_at timestamptz not null default now());
create table public.oauth_authorization_codes(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces(id) on delete cascade,application_id uuid not null references public.developer_applications(id) on delete cascade,user_id uuid not null references auth.users(id),code_hash text not null unique,redirect_uri text not null,scopes text[] not null,code_challenge text not null,expires_at timestamptz not null,used_at timestamptz,created_at timestamptz not null default now());
create table public.oauth_refresh_tokens(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces(id) on delete cascade,application_id uuid not null references public.developer_applications(id) on delete cascade,user_id uuid not null references auth.users(id),token_hash text not null unique,scopes text[] not null,expires_at timestamptz not null,rotated_at timestamptz,replaced_by uuid references public.oauth_refresh_tokens(id),created_at timestamptz not null default now());
create table public.webhook_endpoints(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces(id) on delete cascade,environment public.integration_environment not null,url text not null,secret_hash text not null,events text[] not null,active boolean not null default true,created_at timestamptz not null default now());
create table public.webhook_deliveries(id uuid primary key default gen_random_uuid(),endpoint_id uuid not null references public.webhook_endpoints(id) on delete cascade,event_id text not null,event_type text not null,status text not null,attempts integer not null default 0,response_status integer,next_attempt_at timestamptz,created_at timestamptz not null default now(),unique(endpoint_id,event_id));

create index agent_events_run_created_idx on public.agent_events(run_id,created_at);
create index daily_metrics_site_date_idx on public.daily_site_metrics(site_id,metric_date desc);
create index backlinks_site_seen_idx on public.backlink_observations(site_id,last_seen desc);
create index citations_site_captured_idx on public.ai_citation_probes(site_id,captured_at desc);

do $$ declare t text; begin foreach t in array array['keyword_clusters','site_health_scores','daily_site_metrics','page_metrics','competitors','backlink_observations','ai_citation_probes','internal_link_edges','agent_events','finding_events','content_items','experiment_observations','proposal_file_reviews','brand_profile_versions','knowledge_documents','notification_destinations','notification_deliveries','automation_schedules','workspace_budgets','developer_applications','api_tokens','oauth_authorization_codes','oauth_refresh_tokens','webhook_endpoints','webhook_deliveries'] loop execute format('alter table public.%I enable row level security',t); end loop; end $$;

create or replace function public.can_access_site(target uuid, minimum public.workspace_role default 'viewer') returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from public.sites s where s.id=target and public.is_workspace_member(s.workspace_id,minimum));$$;

do $$ declare t text; begin foreach t in array array['keyword_clusters','site_health_scores','daily_site_metrics','page_metrics','competitors','backlink_observations','ai_citation_probes','internal_link_edges','agent_events','content_items','brand_profile_versions','knowledge_documents','automation_schedules'] loop execute format('create policy %I_site_access on public.%I for all using (public.can_access_site(site_id)) with check (public.can_access_site(site_id,''editor''))',t,t); end loop; end $$;
create policy finding_events_access on public.finding_events for all using(exists(select 1 from public.findings f where f.id=finding_id and public.can_access_site(f.site_id))) with check(exists(select 1 from public.findings f where f.id=finding_id and public.can_access_site(f.site_id,'editor')));
create policy experiment_observations_access on public.experiment_observations for all using(exists(select 1 from public.experiments e where e.id=experiment_id and public.can_access_site(e.site_id))) with check(exists(select 1 from public.experiments e where e.id=experiment_id and public.can_access_site(e.site_id,'editor')));
create policy proposal_file_reviews_access on public.proposal_file_reviews for all using(exists(select 1 from public.proposals p where p.id=proposal_id and public.can_access_site(p.site_id))) with check(exists(select 1 from public.proposals p where p.id=proposal_id and public.can_access_site(p.site_id,'editor')));
do $$ declare t text; begin foreach t in array array['notification_destinations','workspace_budgets','developer_applications','api_tokens','webhook_endpoints'] loop execute format('create policy %I_workspace_access on public.%I for all using (public.is_workspace_member(workspace_id,''admin'')) with check (public.is_workspace_member(workspace_id,''admin''))',t,t); end loop; end $$;
create policy notification_deliveries_read on public.notification_deliveries for select using(exists(select 1 from public.notification_destinations d where d.id=destination_id and public.is_workspace_member(d.workspace_id,'admin')));
create policy webhook_deliveries_read on public.webhook_deliveries for select using(exists(select 1 from public.webhook_endpoints e where e.id=endpoint_id and public.is_workspace_member(e.workspace_id,'admin')));
