#!/usr/bin/env node
import{Command}from"commander";import{chmod,mkdir,readFile,writeFile}from"node:fs/promises";import{homedir,platform}from"node:os";import path from"node:path";import{execFile}from"node:child_process";import{promisify}from"node:util";
const execFileAsync=promisify(execFile),program=new Command(),configPath=path.join(homedir(),".config","seoforge","config.json"),service="ai.seoforge.cli";
type Config={apiUrl:string;environment:"test"|"live";tokenFallback?:string};
async function saveCredential(token:string){if(platform()==="darwin"){await execFileAsync("security",["add-generic-password","-U","-a",process.env.USER||"seoforge","-s",service,"-w",token]);return undefined}return token}
async function loadCredential(c:Config){if(process.env.SEOFORGE_TOKEN)return process.env.SEOFORGE_TOKEN;if(platform()==="darwin"){const{stdout}=await execFileAsync("security",["find-generic-password","-a",process.env.USER||"seoforge","-s",service,"-w"]);return stdout.trim()}if(c.tokenFallback)return c.tokenFallback;throw new Error("Credential not found. Set SEOFORGE_TOKEN or run login again.")}
async function config():Promise<Config&{token:string}>{try{const c=JSON.parse(await readFile(configPath,"utf8"))as Config;return{...c,token:await loadCredential(c)}}catch{throw new Error("Not logged in. Create a scoped token in SEOForge and run: seoforge login --token sf_live_...")}}
async function request(resource:string,init:RequestInit={}){const c=await config();const response=await fetch(`${c.apiUrl}/api/v1/${resource}`,{...init,headers:{authorization:`Bearer ${c.token}`,"content-type":"application/json",...init.headers}});const body=await response.json();if(!response.ok)throw new Error(body.error?.message||`HTTP ${response.status}`);return body.data}
function output(data:unknown,json=true){process.stdout.write(json?`${JSON.stringify(data,null,2)}\n`:`${String(data)}\n`)}
program.name("seoforge").description("Operate an SEOForge autonomous SEO/GEO team").version("0.1.0").option("--json","Emit machine-readable JSON",false);
program.command("login").option("--token <token>").option("--api-url <url>","SEOForge URL","http://localhost:3000").option("--environment <environment>","test or live","live").action(async o=>{const token=o.token||process.env.SEOFORGE_TOKEN;if(!token||!/^sf_(test|live)_/.test(token))throw new Error("Provide a valid sf_test_... or sf_live_... token");const tokenEnvironment=token.startsWith("sf_test_")?"test":"live";if(o.environment!==tokenEnvironment)throw new Error("Token and selected environment do not match");await mkdir(path.dirname(configPath),{recursive:true});const tokenFallback=await saveCredential(token);await writeFile(configPath,JSON.stringify({apiUrl:o.apiUrl.replace(/\/$/,""),environment:o.environment,tokenFallback},null,2),{mode:0o600});await chmod(configPath,0o600);output({authenticated:true,environment:o.environment,credentialStore:platform()==="darwin"?"macOS Keychain":"protected config fallback"})});
program.command("sites").action(async()=>output(await request("sites")));
program.command("site:add").requiredOption("--name <name>").requiredOption("--url <url>").requiredOption("--repo <owner/name>").requiredOption("--installation <id>").option("--branch <branch>","Default branch","main").option("--deploy <provider>","vercel or github_actions","vercel").action(async o=>{const[owner,repositoryName]=o.repo.split("/");output(await request("sites",{method:"POST",body:JSON.stringify({name:o.name,url:o.url,repositoryOwner:owner,repositoryName,defaultBranch:o.branch,githubInstallationId:Number(o.installation),deploymentProvider:o.deploy})}))});
program.command("audit").requiredOption("--site <uuid>").option("--propose","Allow proposal preparation",false).action(async o=>output(await request("audits",{method:"POST",body:JSON.stringify({siteId:o.site,dryRun:!o.propose})})));
const runs=program.command("runs");runs.action(async()=>output(await request("runs")));runs.command("watch").option("--interval <seconds>","Polling interval","5").action(async o=>{let last="";for(;;){const current=JSON.stringify(await request("runs"));if(current!==last){output(JSON.parse(current));last=current}await new Promise(resolve=>setTimeout(resolve,Math.max(1,Number(o.interval))*1000))}});
for(const resource of["findings","proposals","deployments","usage"]as const)program.command(resource).action(async()=>output(await request(resource)));
program.command("approve").description("Approval is deliberately unavailable in the CLI").action(()=>{throw new Error("Open the signed SEOForge web review URL. Merge and deployment require an explicit authenticated UI action.")});
program.command("status").action(async()=>{const[runs,proposals]=await Promise.all([request("runs"),request("proposals")]);output({recentRuns:runs.slice(0,5),pendingProposals:proposals.filter((p:any)=>["ready","checks_pending"].includes(p.state))})});
const mcp=program.command("mcp");mcp.command("install").requiredOption("--client <client>","codex, claude, or cursor").action(async o=>{const c=await config();const url=c.environment==="test"?"https://mcp.test.seoforge.ai/mcp":"https://mcp.seoforge.ai/mcp";const snippets:Record<string,string>={codex:`codex mcp add seoforge --url ${url}`,claude:`claude mcp add --transport http seoforge ${url}`,cursor:JSON.stringify({mcpServers:{seoforge:{url}}},null,2)};if(!snippets[o.client])throw new Error("Supported clients: codex, claude, cursor");output({client:o.client,url,commandOrConfig:snippets[o.client],authentication:"OAuth 2.1 with PKCE opens in the client browser"})});
await program.parseAsync();
